# Generated by Django 5.2.8 on 2025-12-02 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_pastel_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='descuento',
        ),
        migrations.AddField(
            model_name='promocion',
            name='activo_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Desde'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='activo_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Hasta'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='hasta_agotar_stock',
            field=models.BooleanField(default=False, help_text='Si se marca, la promo termina cuando el producto queda sin stock.'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='porcentaje',
            field=models.PositiveIntegerField(blank=True, help_text='Para promos simples de X% de descuento.', null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='porcentaje_segunda_unidad',
            field=models.PositiveIntegerField(blank=True, help_text="Solo para 'Descuento en 2ª unidad'.", null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones', to='adminpanel.producto', verbose_name='Producto en promoción'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo',
            field=models.CharField(choices=[('percentage', 'Descuento porcentaje'), ('second_unit_pct', 'Descuento en 2ª unidad'), ('two_for_one', '2x1')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='etiqueta',
            field=models.CharField(blank=True, help_text="Ej: '2x1', '-20%', 'Oferta'", max_length=50),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promos/', verbose_name='Banner o foto'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='vigencia',
            field=models.CharField(blank=True, help_text="Texto libre (opcional). Ej: 'Del 1 al 15 de junio'.", max_length=100, null=True),
        ),
    ]
