# Generated by Django 5.2.8 on 2025-12-02 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_remove_promocion_descuento_promocion_activo_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activo_desde',
            field=models.DateField(blank=True, help_text='Opcional: fecha desde la que se activa la promoción.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activo_hasta',
            field=models.DateField(blank=True, help_text='Opcional: fecha hasta la que se aplica la promoción.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Opcional: texto que se muestra bajo el título.', null=True, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='enlace_categoria',
            field=models.CharField(blank=True, help_text='Slug de categoría para el botón (vitrina, tortas, postres). Opcional.', max_length=30),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='etiqueta',
            field=models.CharField(blank=True, help_text="Ej: '2x1', '-15%', 'Oferta'. Opcional.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='hasta_agotar_stock',
            field=models.BooleanField(default=False, help_text='Si está marcado, no se aplica cuando el producto queda sin stock.'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Solo para 'Descuento %': porcentaje sobre todas las unidades.", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje_segunda_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Solo para 'segunda unidad': % de descuento en la 2ª unidad de cada par.", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto al que aplica esta promoción (puede ser opcional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='adminpanel.producto'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='tipo',
            field=models.CharField(choices=[('2x1', '2x1 (paga 1, lleva 2)'), ('porcentaje', 'Descuento % sobre todas las unidades'), ('segunda_unidad', 'Descuento % en la segunda unidad')], default='porcentaje', help_text='Define cómo se aplica el descuento.', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='vigencia',
            field=models.CharField(blank=True, help_text="Ej: 'Hasta el 31/12' o 'Hasta agotar stock'. Opcional.", max_length=100, null=True),
        ),
    ]
