# Generated by Django 5.2.8 on 2025-12-02 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_promocion_activa_alter_promocion_activo_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='activo_desde',
            field=models.DateField(blank=True, help_text='Fecha desde la cual está activa. Opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activo_hasta',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual está activa. Opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción visible al cliente. Opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='enlace_categoria',
            field=models.CharField(blank=True, choices=[('', '--- Sin categoría ---'), ('vitrina', 'Repostería de vitrina'), ('tortas', 'Tortas'), ('postres', 'Postres'), ('todas', 'Todas las categorías')], help_text='Dónde se aplicará/mostrará la promo: una categoría específica o todas. Déjalo vacío si es sólo para un producto concreto.', max_length=20, null=True, verbose_name='Categoría objetivo'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Texto corto que se muestra como badge (ej: 2x1, -30%). Opcional.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='hasta_agotar_stock',
            field=models.BooleanField(default=False, help_text='Si se marca, la promo se detiene cuando el stock del producto llega a 0.'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promos/'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje',
            field=models.PositiveIntegerField(blank=True, help_text='Descuento en %, por ejemplo 20 para 20%. Opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje_segunda_unidad',
            field=models.PositiveIntegerField(blank=True, help_text='Descuento % sobre la segunda unidad. Opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Opcional. Si se define, la promo aplica a este producto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='adminpanel.producto'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='tipo',
            field=models.CharField(choices=[('2x1', '2x1'), ('porcentaje', 'Descuento % general'), ('segunda_unidad', '% en segunda unidad')], help_text='Tipo de promoción: 2x1, porcentaje a todo, o porcentaje en la segunda unidad.', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='vigencia',
            field=models.CharField(blank=True, help_text="Texto libre de vigencia (ej: 'Hasta el 31/12' o 'Hasta agotar stock'). Opcional.", max_length=100, null=True),
        ),
    ]
