# Generated by Django 5.2.8 on 2025-12-02 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_promocion_activo_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='categoria_objetivo',
            field=models.CharField(blank=True, choices=[('', 'Solo este producto'), ('vitrina', 'Repostería de vitrina'), ('postres', 'Postres'), ('tortas', 'Tortas'), ('all', 'Todas las categorías')], default='', help_text='Si eliges una categoría, la promo se aplica a TODOS los productos de esa categoría.', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Marca si la promo está activa.'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activo_desde',
            field=models.DateField(blank=True, help_text='Fecha desde la que la promo está activa. Opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activo_hasta',
            field=models.DateField(blank=True, help_text='Fecha hasta la que la promo está activa. Opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción visible para el cliente. Opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='enlace_categoria',
            field=models.CharField(blank=True, choices=[('', 'Sin botón'), ('vitrina', 'Repostería de vitrina'), ('postres', 'Postres'), ('tortas', 'Tortas')], default='', help_text='Categoría a la que apuntará el botón en la web. Opcional.', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='etiqueta',
            field=models.CharField(blank=True, default='', help_text="Texto corto que se muestra como badge (ej: '2x1', '-30%'). Opcional.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='hasta_agotar_stock',
            field=models.BooleanField(default=False, help_text='Si se marca, la promo se desactiva cuando el producto se queda sin stock.'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen opcional para la tarjeta de promoción.', null=True, upload_to='promos/'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje',
            field=models.PositiveIntegerField(blank=True, help_text="Solo para tipo 'porcentaje'. Ej: 20 para 20%.", null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje_segunda_unidad',
            field=models.PositiveIntegerField(blank=True, help_text="Solo para tipo 'segunda_unidad'. Ej: 50 para 50% en la segunda unidad.", null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto específico al que se aplica la promo. Déjalo vacío si usarás una categoría.', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.producto'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='tipo',
            field=models.CharField(choices=[('2x1', '2x1'), ('porcentaje', 'Descuento porcentaje'), ('segunda_unidad', 'Descuento en segunda unidad')], help_text='Tipo de promoción (2x1, porcentaje, segunda unidad).', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='vigencia',
            field=models.CharField(blank=True, default='', help_text="Texto informativo (ej: 'Hasta el 30/06 o hasta agotar stock'). Opcional.", max_length=100, null=True),
        ),
    ]
