# Generated by Django 5.2.8 on 2025-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_promocion_categoria_objetivo_alter_promocion_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='enlace_categoria',
            field=models.CharField(blank=True, choices=[('', 'Sin categoria'), ('vitrina', 'Repostería de vitrina'), ('postres', 'Postres'), ('tortas', 'Tortas')], default='', help_text='Categoría a la que apuntará el botón en la web. Opcional.', max_length=20),
        ),
    ]
