# Generated by Django 5.2.8 on 2025-11-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_promocion_descuento_promocion_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Promoción'),
        ),
    ]
